# Generated by Django 5.0.1 on 2024-02-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0005_error_logs_exceptionname'),
    ]

    operations = [
        migrations.AddField(
            model_name='error_logs',
            name='log_file_type_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mobileservices_logs',
            name='log_file_type_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reports_logs',
            name='log_file_type_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='youtility_logs',
            name='log_file_type_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
